services:
  influxdb3-core:
    image: influxdb:3-core
    container_name: influxdb3-core
    user: "1000:1000"
    ports:
      - "8181:8181"
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    volumes:
      - ${DATA_DIR}/influxdb3/data:/var/lib/influxdb3/data
      - ${DATA_DIR}/influxdb3/plugins:/var/lib/influxdb3/plugins
    restart: unless-stopped

  influxdb3-explorer:
    image: influxdata/influxdb3-ui:1.6.2
    container_name: influxdb3-explorer
    command: ["--mode=admin"]
    ports:
      - "8888:80"
    env_file:
      - .env
    volumes:
      - ${DATA_DIR}/explorer/db:/db:rw
      - ${DATA_DIR}/explorer/config:/app-root/config:ro
    environment:
      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
    restart: unless-stopped
    depends_on:
      - influxdb3-core
  postgres:
    image: postgres:16-alpine
    container_name: postgresdb
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${DATA_DIR}/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  # cloudflared:
  #   image: cloudflare/cloudflared:latest
  #   container_name: cloudflared
  #   restart: unless-stopped
  #   command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
  #   env_file: 
  #     - .env

  # dashboard:
  #   image: dashboard
  #   build:
  #     context: .
  #   container_name: dashboard
  #   environment:
  #     - APP_PORT=${APP_PORT}
  #   ports:
  #   - "${APP_PORT}:${APP_PORT}"
  #   restart: unless-stopped